export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CATEGORY_CREATED = 'CATEGORY_CREATED';
export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';
export const CATEGORY_EDITED = 'CATEGORY_EDITED';
export const CATEGORY_DELETED = 'CATEGORY_DELETED';
